CREATE TABLE addr(
	username VARCHAR2(20),
	tel VARCHAR2(20),
	email VARCHAR2(40),
	sex VARCHAR2(20));
	
CREATE TABLE addrbook(
	ab_id NUMBER(11) NOT NULL,
	ab_name VARCHAR2(15) NOT NULL,
	ab_email VARCHAR2(50) DEFAULT NULL,
	ab_comdept VARCHAR2(20) NOT NULL,
	ab_birth VARCHAR2(20) NOT NULL,
	ab_tel VARCHAR2(20) DEFAULT NULL,
	ab_memo VARCHAR2(100) DEFAULT NULL,
	CONSTRAINT id_pk PRIMARY KEY (ab_id));


CREATE SEQUENCE SEQ_ID START WITH 1 INCREMENT BY 1;


CREATE TABLE LOGINADDR(
	AD_ID NUMBER(10) NOT NULL,
	AD_NAME VARCHAR2(15) NOT NULL,
	AD_PSW VARCHAR2(10) NOT NULL,
	AD_EMAIL VARCHAR2(50) DEFAULT NULL,
	AD_BIRTH VARCHAR2(10) NOT NULL,
	AD_MEMO VARCHAR2(100) DEFAULT NULL,
	CONSTRAINT primary_id PRIMARY KEY(AD_ID));
